kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ${CLUSTER_NAME}

networking:
  apiServerAddress: "127.0.0.1"

nodes:
  - role: control-plane
    image: kindest/node:${K8S_VERSION}
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: ${NGINX_HTTP_PORT}
        hostPort: ${NGINX_HTTP_PORT}
        protocol: TCP
      - containerPort: ${NGINX_HTTPS_PORT}
        hostPort: ${NGINX_HTTPS_PORT}
        protocol: TCP
      - containerPort: ${ISTIO_NODEPORT_HTTP}
        hostPort: ${ISTIO_HTTP_PORT}
        protocol: TCP
      - containerPort: ${ISTIO_NODEPORT_HTTPS}
        hostPort: ${ISTIO_HTTPS_PORT}
        protocol: TCP
    extraMounts:
      - hostPath: ${STORAGE_ROOT}
        containerPath: ${STORAGE_ROOT}

  - role: worker
    image: kindest/node:${K8S_VERSION}
    extraMounts:
      - hostPath: ${STORAGE_ROOT}
        containerPath: ${STORAGE_ROOT}

  - role: worker
    image: kindest/node:${K8S_VERSION}
    extraMounts:
      - hostPath: ${STORAGE_ROOT}
        containerPath: ${STORAGE_ROOT}
